import { DEFAULT_CATEGORIES } from './constants'
import { createId } from './dates'
import { defaultCompany } from './business'
import { defaultSubscription } from './subscription'
import { BUSINESS_FEATURE_IDS } from './features'

export function getEmptyState(profile = {}) {
  return {
    profile: {
      name: profile.name?.trim() || '',
      workspace: profile.workspace?.trim() || 'Personal workspace',
      currency: profile.currency || 'USD',
      language: profile.language || 'en',
      geminiApiKey: profile.geminiApiKey || '',
      enabledBusinessFeatures: [...BUSINESS_FEATURE_IDS],
    },
    subscription: defaultSubscription(),
    company: defaultCompany(),
    departments: [],
    employees: [],
    clients: [],
    projects: [],
    vendors: [],
    shops: [],
    invoices: [],
    inventory: [],
    bills: [],
    categories: DEFAULT_CATEGORIES,
    transactions: [],
    budgets: [],
    goals: [],
    recurring: [],
  }
}

export function getSeedState() {
  const now = new Date().toISOString()
  const deptOps = 'dept-operations'
  const deptDesign = 'dept-design'
  const deptSales = 'dept-sales'
  const empJordan = 'emp-jordan'
  const empSam = 'emp-sam'
  const empRiley = 'emp-riley'
  const clientHarbor = 'client-harbor'
  const clientPixel = 'client-pixel'
  const projectBrand = 'proj-brand'
  const projectSite = 'proj-site'
  const vendorAws = 'vendor-aws'
  const vendorWeWork = 'vendor-wework'
  const vendorDelta = 'vendor-delta'
  const shopMarket = 'shop-market'
  const shopCafe = 'shop-cafe'
  const shopMart = 'shop-oak'

  const shopHistory = [
    { month: '2026-03', sales: [8200, 5400, 3600], inventory: [4100, 1800, 1600] },
    { month: '2026-04', sales: [8450, 5800, 3400], inventory: [4300, 1900, 1500] },
    { month: '2026-05', sales: [9100, 6100, 3900], inventory: [4600, 2100, 1700] },
    { month: '2026-06', sales: [8800, 7200, 4100], inventory: [4400, 2400, 1800] },
    { month: '2026-07', sales: [10200, 6900, 4300], inventory: [5100, 2300, 1900] },
    { month: '2026-08', sales: [9800, 7500, 4700], inventory: [4900, 2500, 2100] },
  ]
  const shopMeta = [
    { id: shopMarket, name: 'Market Street Grocery', rent: 2400 },
    { id: shopCafe, name: 'Riverside Cafe', rent: 1800 },
    { id: shopMart, name: 'Oak Hill Mart', rent: 1200 },
  ]
  const shopTransactions = shopHistory.flatMap((row) =>
    shopMeta.flatMap((shop, index) => [
      {
        id: createId(),
        name: `${shop.name} sales`,
        amount: row.sales[index],
        type: 'income',
        category: 'Shop sales',
        date: `${row.month}-28`,
        note: 'Register close',
        paymentMethod: 'Cash',
        createdAt: now,
        shopId: shop.id,
        status: 'recorded',
        billable: false,
        reimbursable: false,
        taxRate: 0,
        taxAmount: 0,
      },
      {
        id: createId(),
        name: `${shop.name} inventory`,
        amount: row.inventory[index],
        type: 'expense',
        category: 'Inventory',
        date: `${row.month}-06`,
        note: 'Supplier restock',
        paymentMethod: 'Bank',
        createdAt: now,
        shopId: shop.id,
        status: 'recorded',
        billable: false,
        reimbursable: false,
        taxRate: 0,
        taxAmount: 0,
      },
      {
        id: createId(),
        name: `${shop.name} rent`,
        amount: shop.rent,
        type: 'expense',
        category: 'Home',
        date: `${row.month}-01`,
        note: 'Location lease',
        paymentMethod: 'Bank',
        createdAt: now,
        shopId: shop.id,
        status: 'recorded',
        billable: false,
        reimbursable: false,
        taxRate: 0,
        taxAmount: 0,
      },
    ]),
  )

  return {
    profile: {
      name: 'Jordan Davis',
      workspace: 'Personal workspace',
      currency: 'USD',
      language: 'en',
    },
    subscription: {
      plan: 'free',
      status: 'inactive',
      billing: 'monthly',
      startedAt: null,
      renewsAt: null,
      canceledAt: null,
    },
    company: {
      legalName: 'Northwind Studio LLC',
      taxId: '88-2145091',
      address: '412 Market Street, Austin, TX',
      defaultTaxRate: 8,
    },
    departments: [
      { id: deptOps, name: 'Operations', code: 'OPS' },
      { id: deptDesign, name: 'Design', code: 'DES' },
      { id: deptSales, name: 'Sales', code: 'SAL' },
    ],
    employees: [
      { id: empJordan, name: 'Jordan Davis', role: 'admin', departmentId: deptOps, email: 'jordan@northwind.studio' },
      { id: empSam, name: 'Sam Patel', role: 'manager', departmentId: deptDesign, email: 'sam@northwind.studio' },
      { id: empRiley, name: 'Riley Chen', role: 'employee', departmentId: deptSales, email: 'riley@northwind.studio' },
    ],
    clients: [
      { id: clientHarbor, name: 'Harbor & Co', contact: 'Maya Ellis', email: 'maya@harbor.co' },
      { id: clientPixel, name: 'Pixel North', contact: 'Chris Lang', email: 'chris@pixelnorth.io' },
    ],
    projects: [
      { id: projectBrand, name: 'Brand refresh', clientId: clientHarbor, status: 'active' },
      { id: projectSite, name: 'Website rebuild', clientId: clientPixel, status: 'active' },
    ],
    vendors: [
      { id: vendorAws, name: 'Amazon Web Services', category: 'Infrastructure' },
      { id: vendorWeWork, name: 'WeWork', category: 'Office' },
      { id: vendorDelta, name: 'Delta Air Lines', category: 'Travel' },
    ],
    shops: [
      { id: shopMarket, name: 'Market Street Grocery', city: 'Austin', type: 'grocery' },
      { id: shopCafe, name: 'Riverside Cafe', city: 'Austin', type: 'cafe' },
      { id: shopMart, name: 'Oak Hill Mart', city: 'Austin', type: 'retail' },
    ],
    categories: DEFAULT_CATEGORIES,
    transactions: [
      {
        id: createId(),
        name: 'Acme Studio LLC',
        amount: 4200,
        type: 'income',
        category: 'Salary',
        date: '2026-08-01',
        note: 'August salary',
        paymentMethod: 'Bank',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'Design sprint',
        amount: 800,
        type: 'income',
        category: 'Freelance',
        date: '2026-08-15',
        note: 'Weekend project',
        paymentMethod: 'Bank',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'Rent',
        amount: 1180,
        type: 'expense',
        category: 'Home',
        date: '2026-08-01',
        note: 'August rent',
        paymentMethod: 'Bank',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'City Power',
        amount: 95,
        type: 'expense',
        category: 'Utilities',
        date: '2026-08-05',
        note: '',
        paymentMethod: 'Bank',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'Northside Gym',
        amount: 45,
        type: 'expense',
        category: 'Health',
        date: '2026-08-03',
        note: 'Monthly membership',
        paymentMethod: 'Card',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'Netflix',
        amount: 15.99,
        type: 'expense',
        category: 'Subscriptions',
        date: '2026-08-10',
        note: '',
        paymentMethod: 'Card',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'Notion',
        amount: 12,
        type: 'expense',
        category: 'Subscriptions',
        date: '2026-08-30',
        note: '',
        paymentMethod: 'Card',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'River Pharmacy',
        amount: 32,
        type: 'expense',
        category: 'Health',
        date: '2026-08-18',
        note: '',
        paymentMethod: 'Card',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'CityCom Transit',
        amount: 26.5,
        type: 'expense',
        category: 'Transport',
        date: '2026-08-22',
        note: 'Weekly pass',
        paymentMethod: 'Wallet',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'Uber',
        amount: 18.4,
        type: 'expense',
        category: 'Transport',
        date: '2026-08-20',
        note: '',
        paymentMethod: 'Wallet',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'The Corner Cafe',
        amount: 8.75,
        type: 'expense',
        category: 'Food & dining',
        date: '2026-08-24',
        note: '',
        paymentMethod: 'Card',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'Olive & Thyme',
        amount: 64,
        type: 'expense',
        category: 'Food & dining',
        date: '2026-08-16',
        note: 'Dinner with friends',
        paymentMethod: 'Card',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'Whole Foods Market',
        amount: 84.2,
        type: 'expense',
        category: 'Groceries',
        date: '2026-08-31',
        note: 'Weekly shop',
        paymentMethod: 'Card',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'Green Basket',
        amount: 52.3,
        type: 'expense',
        category: 'Groceries',
        date: '2026-08-12',
        note: '',
        paymentMethod: 'Card',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'July salary',
        amount: 4200,
        type: 'income',
        category: 'Salary',
        date: '2026-07-01',
        note: '',
        paymentMethod: 'Bank',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'July rent',
        amount: 1180,
        type: 'expense',
        category: 'Home',
        date: '2026-07-01',
        note: '',
        paymentMethod: 'Bank',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'July groceries',
        amount: 210,
        type: 'expense',
        category: 'Groceries',
        date: '2026-07-14',
        note: '',
        paymentMethod: 'Card',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'July dining',
        amount: 140,
        type: 'expense',
        category: 'Food & dining',
        date: '2026-07-19',
        note: '',
        paymentMethod: 'Card',
        createdAt: now,
      },
      {
        id: createId(),
        name: 'Amazon Web Services',
        amount: 142,
        type: 'expense',
        category: 'Subscriptions',
        date: '2026-08-08',
        note: 'Cloud hosting',
        paymentMethod: 'Card',
        createdAt: now,
        employeeId: empJordan,
        departmentId: deptOps,
        vendorId: vendorAws,
        billable: false,
        reimbursable: false,
        taxRate: 0,
        taxAmount: 0,
        status: 'approved',
      },
      {
        id: createId(),
        name: 'Harbor client dinner',
        amount: 86.4,
        type: 'expense',
        category: 'Food & dining',
        date: '2026-08-19',
        note: 'Onsite dinner after review',
        paymentMethod: 'Card',
        createdAt: now,
        employeeId: empRiley,
        departmentId: deptSales,
        clientId: clientHarbor,
        projectId: projectBrand,
        billable: true,
        reimbursable: true,
        taxRate: 8,
        taxAmount: 6.91,
        status: 'submitted',
      },
      {
        id: createId(),
        name: 'Figma organization',
        amount: 45,
        type: 'expense',
        category: 'Subscriptions',
        date: '2026-08-11',
        note: '',
        paymentMethod: 'Card',
        createdAt: now,
        employeeId: empSam,
        departmentId: deptDesign,
        billable: false,
        reimbursable: false,
        taxRate: 0,
        taxAmount: 0,
        status: 'approved',
      },
      {
        id: createId(),
        name: 'WeWork day pass',
        amount: 65,
        type: 'expense',
        category: 'Home',
        date: '2026-08-14',
        note: 'Client workshop space',
        paymentMethod: 'Card',
        createdAt: now,
        employeeId: empRiley,
        departmentId: deptSales,
        vendorId: vendorWeWork,
        clientId: clientPixel,
        projectId: projectSite,
        billable: true,
        reimbursable: true,
        taxRate: 0,
        taxAmount: 0,
        status: 'reimbursed',
      },
      {
        id: createId(),
        name: 'Delta flight AUS-SFO',
        amount: 380,
        type: 'expense',
        category: 'Travel',
        date: '2026-08-21',
        note: 'Kickoff travel',
        paymentMethod: 'Card',
        createdAt: now,
        employeeId: empSam,
        departmentId: deptDesign,
        vendorId: vendorDelta,
        clientId: clientPixel,
        projectId: projectSite,
        billable: true,
        reimbursable: true,
        taxRate: 0,
        taxAmount: 0,
        status: 'submitted',
      },
      ...shopTransactions,
    ],
    budgets: [
      { id: createId(), category: 'Home', amount: 1300 },
      { id: createId(), category: 'Groceries', amount: 400 },
      { id: createId(), category: 'Food & dining', amount: 350 },
      { id: createId(), category: 'Transport', amount: 200 },
      { id: createId(), category: 'Subscriptions', amount: 80 },
      { id: createId(), category: 'Health', amount: 120 },
      { id: createId(), category: 'Utilities', amount: 160 },
    ],
    goals: [
      {
        id: createId(),
        name: 'Emergency fund',
        targetAmount: 5000,
        currentAmount: 2100,
        deadline: '2026-12-31',
        note: 'Three months of expenses',
      },
      {
        id: createId(),
        name: 'Lisbon trip',
        targetAmount: 1800,
        currentAmount: 640,
        deadline: '2027-03-15',
        note: 'Flights and lodging',
      },
      {
        id: createId(),
        name: 'New laptop',
        targetAmount: 1400,
        currentAmount: 320,
        deadline: '2026-11-30',
        note: '',
      },
    ],
    recurring: [
      {
        id: createId(),
        name: 'Rent',
        amount: 1180,
        type: 'expense',
        category: 'Home',
        frequency: 'monthly',
        nextDate: '2026-09-01',
        paymentMethod: 'Bank',
        note: 'Monthly rent',
      },
      {
        id: createId(),
        name: 'Salary',
        amount: 4200,
        type: 'income',
        category: 'Salary',
        frequency: 'monthly',
        nextDate: '2026-09-01',
        paymentMethod: 'Bank',
        note: 'Monthly salary',
      },
      {
        id: createId(),
        name: 'Notion',
        amount: 12,
        type: 'expense',
        category: 'Subscriptions',
        frequency: 'monthly',
        nextDate: '2026-09-30',
        paymentMethod: 'Card',
        note: '',
      },
    ],
    invoices: [
      {
        id: 'inv-harbor',
        number: 'INV-0001',
        party: 'Harbor Brands',
        clientId: clientHarbor,
        date: '2026-08-12',
        dueDate: '2026-08-26',
        amount: 2400,
        taxAmount: 192,
        status: 'sent',
        notes: 'Brand sprint',
        createdAt: now,
      },
      {
        id: 'inv-pixel',
        number: 'INV-0002',
        party: 'Pixel & Pine',
        clientId: clientPixel,
        date: '2026-08-28',
        dueDate: '2026-09-12',
        amount: 1800,
        taxAmount: 144,
        status: 'sent',
        notes: 'Site retainers',
        createdAt: now,
      },
    ],
    bills: [
      {
        id: 'bill-aws',
        party: 'Amazon Web Services',
        vendorId: vendorAws,
        date: '2026-08-08',
        dueDate: '2026-09-08',
        amount: 142,
        status: 'unpaid',
        notes: 'August cloud',
        createdAt: now,
      },
      {
        id: 'bill-wework',
        party: 'WeWork',
        vendorId: vendorWeWork,
        date: '2026-08-01',
        dueDate: '2026-08-15',
        amount: 890,
        status: 'unpaid',
        notes: 'Studio desk',
        createdAt: now,
      },
    ],
    inventory: [
      {
        id: 'stk-beans',
        name: 'Coffee beans 1kg',
        sku: 'CAFE-BEAN',
        qty: 8,
        unitCost: 14,
        sellPrice: 22,
        reorderAt: 12,
        shopId: shopCafe,
      },
      {
        id: 'stk-milk',
        name: 'Whole milk crate',
        sku: 'CAFE-MILK',
        qty: 4,
        unitCost: 18,
        sellPrice: 28,
        reorderAt: 6,
        shopId: shopCafe,
      },
      {
        id: 'stk-rice',
        name: 'Basmati 10kg',
        sku: 'MKT-RICE',
        qty: 22,
        unitCost: 16,
        sellPrice: 24,
        reorderAt: 8,
        shopId: shopMarket,
      },
    ],
  }
}
